# AP25122060013

# 1.Create a one dimensional numpy array from a python list

In [ ]:
import numpy as np
a=[1,7,87,8]
print(np.array(a))

[ 1  7 87  8]


In [ ]:
print(10*"*")
print("2 dimesional array")
b=np.array([[4,7,8],[9,63,8]])
print(b)
print(b.shape)
print(b.size)
print(b.ndim)

**********
2 dimesional array
[[ 4  7  8]
 [ 9 63  8]]
(2, 3)
6
2


In [ ]:
print(10*"*")
c=[[1,8,6,2],[78,98,65,7]]
print(np.array(c))
print(np.array(c).shape)
print(np.array(c).size)

**********
[[ 1  8  6  2]
 [78 98 65  7]]
(2, 4)
8


# 2.Create a 2 dimensional array of size 3*3 filled with zeros

In [ ]:
print(10*"*")
print(np.zeros((3,3)))#=>2 problem
print(10*"*")

**********
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
**********


# 3.create array of 5 random numbers between 0 and 1

In [ ]:
print(np.random.rand(5))#between 0 and 1
print(np.random.uniform(0,5,size=5))#between 0 and 5
print(np.random.randint(1,10,size=5))

[0.65504003 0.56902798 0.34491802 0.58421991 0.27206877]
[4.19433171 2.61491747 4.49426781 1.18860181 4.39048618]
[5 3 4 6 1]


#  4.Slicing a numpy array to make sub  matrix

In [ ]:
print(10*"*")
arr=np.array([[5,9,3,8],[12,87,54,65]])
c=arr[:2,:2]#end s inclusive
print(c)
# resahpe
print(10*"*")
c=arr.reshape(4,2)
print(c)

**********
[[ 5  9]
 [12 87]]
**********
[[ 5  9]
 [ 3  8]
 [12 87]
 [54 65]]


# 5.Reshape one dimensional array of 12 elements into 3*4 matrix

In [ ]:
print(20*"*")
x=np.array([9,8,7,5,6,12,3,4,8,84,12,32])
k=np.arange(12,24)
print(x.reshape(3,4))
print(k.reshape(3,4))

********************
[[ 9  8  7  5]
 [ 6 12  3  4]
 [ 8 84 12 32]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


# 6.Compute dot product of two matrices

In [ ]:
print(10*"*")
# dot product
k=np.arange(1,7).reshape(2,3)#7is exclusive
p=np.arange(6,12).reshape(3,2)
print(k)
print(p)
print(np.dot(k,p))
print(20*"*")
q=np.arange(12).reshape(3,4)
print(q)
w=np.arange(12,24).reshape(4,3)
print(w)
print(np.dot(w,q))
print(10*"*")

**********
[[1 2 3]
 [4 5 6]]
[[ 6  7]
 [ 8  9]
 [10 11]]
[[ 52  58]
 [124 139]]
********************
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
[[164 203 242 281]
 [200 248 296 344]
 [236 293 350 407]
 [272 338 404 470]]
**********


# 7.Perform arithematic operations of two arrays

In [ ]:
d=np.arange(12,18).reshape(2,3)
m=np.arange(18,24).reshape(2,3)
print(d+m)
print(d*m)
print(d-m)
print(5*"*")

[[30 32 34]
 [36 38 40]]
[[216 247 280]
 [315 352 391]]
[[-6 -6 -6]
 [-6 -6 -6]]
*****


# 8.Convert nd array to 1D

In [ ]:
a = np.array([[1, 2], [3, 4],[9,6],[7,8,]])
# print(np.transpose(a))
print(np.trace(a))#sum
print(np.ravel(a))
print(a.flatten())
print(a.reshape(-1))

print(5*"*")
print(a.sum(axis=1))
print(a.sum(axis=0))

5
[1 2 3 4 9 6 7 8]
[1 2 3 4 9 6 7 8]
[1 2 3 4 9 6 7 8]
*****
[ 3  7 15 15]
[20 20]


# 9.Dtypes and Conversion

In [ ]:
# dt = np.dtype([('name','U10'), ('age','i4'), ('marks','f4')])#hetrogenous data
data = np.array([('Alice',25,88.5), ('Bob',30,72.3)],dtype=object)
print(data.dtype)


# homogenoous data
age=np.array(10)
print(age.dtype)

k=np.array(15.333)
print(k.dtype)

k=np.array([[11,12,23],[56,7,8]])
print(k.dtype)

m=np.array("Name")
print(m.dtype)

t=np.array(True)
print(t.dtype)

arr = np.array([1, "hello", 3.5])
print(arr.dtype)
# convert int into float
age=age.astype(np.float32)
print(age.dtype)

nums = np.array([10, 20, 30])
s = nums.astype(str)
print(s.dtype)

object
int64
float64
int64
<U4
bool
<U32
float32
<U21


# 10.Binomial Distribution & PMF
### PMF → binom.pmf(k, n, p) → exact probability of k successes.
### CDF → binom.cdf(k, n, p) → probability of ≤ k successes.
### SF → binom.sf(k, n, p) → probability of > k successes.***


In [ ]:
import numpy as np
A=np.array([[1,2],
            [3,4]])
B=np.array([[5,6],
            [7,8]])

In [ ]:
# Probability (approx by many experiments)
import math
from scipy.stats import binom
p = binom.pmf(500, 1000, 0.5)
print("P(500 heads) =", p)

# It models the probability of getting exactly k successes in n independent trials,
# P(X=6) when n=10, p=0.5
prob = binom.pmf(6, n=10, p=0.5)
print(prob)  # 0.205078125


P(500 heads) = 0.025225018178360824
0.2050781249999999


In [ ]:
print(np.dot(A,B))

[[19 22]
 [43 50]]


In [ ]:
np.linalg.det(A)

np.float64(-2.0000000000000004)

In [ ]:
c=np.linalg.inv(A)
print(c)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [ ]:
# linear equations
# Ax=b
b=np.array([5,11])
x=np.linalg.solve(A,b)
print(x)

[1. 2.]


In [ ]:
# eigen values eigen vectors
# vals->eigen values,vecs->eigen vectors
vals,vecs=np.linalg.eig(A)

In [ ]:
print(vals)
print(20*"*")
print(vecs)

[-0.37228132  5.37228132]
********************
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [ ]:
# mahbitude or norm
c=np.linalg.norm([3,4])
print(c)

5.0


In [ ]:
np.linalg.matrix_rank(A)
print(A.T)

[[1 3]
 [2 4]]


In [ ]:
# SVD
U, S, Vt = np.linalg.svd(A)


In [ ]:
print(U)

[[-0.40455358 -0.9145143 ]
 [-0.9145143   0.40455358]]


In [ ]:
print(S)

[5.4649857  0.36596619]


In [ ]:
print(Vt)

[[-0.57604844 -0.81741556]
 [ 0.81741556 -0.57604844]]


In [ ]:
from scipy import stats

data=np.array([1,2,3,4,5,6,7,8,9,10])
print(stats.mode(data))


ModeResult(mode=np.int64(1), count=np.int64(1))


In [ ]:
np.var(data)


np.float64(8.25)

In [ ]:
np.std(data)


np.float64(2.8722813232690143)

In [ ]:
np.min(data)
np.max(data)


np.int64(10)

In [ ]:
np.percentile(data, 25)   # Q1
np.percentile(data, 50)   # Median
np.percentile(data, 75)   # Q3


np.float64(7.75)

In [ ]:
x = np.array([1, 2, 3, 4, 55,4])
y = np.array([2, 4, 6, 8, 10,95])

np.corrcoef(x, y)


array([[ 1.        , -0.11506747],
       [-0.11506747,  1.        ]])

In [ ]:
import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6]])


In [ ]:
B = A.flatten()


In [ ]:
B

array([1, 2, 3, 4, 5, 6])

In [ ]:
C = A.ravel()
C

array([1, 2, 3, 4, 5, 6])

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6])
b = a.reshape((2, 3))

print(b)

[[1 2 3]
 [4 5 6]]
